[package]
name = "examples"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
suave-alloy = { path = "../crates/suave-alloy" }

<<<<<<< Updated upstream
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "e7542d7", features = [
    "providers",
    "rpc-types-trace",
    "signer-wallet",
    "network",
    "signers",
    "contract",
    "provider-http",
    "rpc-client",
    "rpc-types-eth",
    "consensus",
    "eips",
    "serde",
] }
=======
alloy.workspace = true
>>>>>>> Stashed changes
tokio.workspace = true
eyre.workspace = true

[[example]]
name = "submit_ccr"
path = "submit_ccr.rs"

[[example]]
name = "callbuilder_ccr"
path = "callbuilder_ccr.rs"